void cache_init (void);
void cache_destroy (void);
void cache_sector_read (unsigned, void *, unsigned, unsigned);
void cache_sector_write (unsigned, const void *, unsigned, unsigned);
void cache_sector_lock (unsigned);
void cache_sector_unlock (unsigned);
void cache_sector_add (unsigned);
void cache_sector_fetch_async (unsigned);
void cache_sector_close (unsigned);
void cache_sector_remove (unsigned);
